/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package middleware;

import java.io.IOException;
import java.util.concurrent.TimeoutException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException, TimeoutException {
       QueueListener.consumeMessage();
    }
}
